#!/bin/sh
#[ "$PPP_IFACE" != "ppp0" ] || exit 0 
iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE 
iptables -A FORWARD -i ppp0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i eth0 -o ppp0 -j ACCEPT
